# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c15b446af8ee02770e518b1967818040a55f1a853670e5b00909aff23d2bc2598d286d58910eb1caab2ec8e4e579fec013e7852181ef2ca1c63b4ffca8364c34

test:
  secret_key_base: 7ba6bc063045d2c181aea40415ae74996abd46716c4eb86f697020e952291d09175056d078f942cdc3885231e2c8edba7f6e5b5c66327c82e4247279f9c4e780

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
